export const ACTION_TYPE = {
    SET_USER: 'SET_USER',
    LOGOUT: 'LOGOUT',
    SEARCH_PRODUCT: 'SEARCH_PRODUCT',
    SET_CATEGORIES: 'SET_CATEGORIES',
    LOAD_PRODUCTS: 'LOAD_PRODUCTS',
    SELECT_PRODUCT: 'SELECT_PRODUCT',
    LOAD_CATEGORIES: 'LOAD_CATEGORIES',
}